const router = require('express').Router();
const auth = require('../middleware/auth');
const controller = require('../controllers/expenseController');
router.use(auth);
router.get('/', controller.list);
router.post('/', controller.create);
router.get('/:id', controller.getOne);
router.put('/:id', controller.update);
router.delete('/:id', controller.remove);
module.exports = router;
